name: perf_api
version: 0.0.9
author: Pavel Jbanov <pavelgj@gmail.com>
homepage: https://github.com/google/perf_api.dart
description: A simple profiling instrumentation API

dev_dependencies:
  unittest: '>=0.9.0 <0.12.0'
